### ISSUE TITLE
Examples are not displayed dynamically 

### ISSUE THREAD

**Issue by krzysztof99xd** [tilburgsciencehub/website-flask#10]
So when I was working on implementing the copy code button I found out that example pages are not displayed dynamically.  
Whenever I was changing on the page content-wise (for example adding new words in the text). I noticed that it does not change. 
I tried on the other pages, for example on home page and it does change there. 

I believe that the issue may be with wrong URI. Below the URI the website tries to access:

![WrongURIPath](https://github.com/tilburgsciencehub/website-flask/assets/83342963/112b9ce3-9f31-40ae-9a3a-92ca112465ca)

And here the actual URI from the project structure (we can see it is `/static/json/cards.js`) :
 
![FinalStructure](https://github.com/tilburgsciencehub/website-flask/assets/83342963/bf26794f-0536-49ec-9cb0-2be7dae95657)

In this example you can see that there is an additional word /examples/ there. I think that may be the reason. 

UPDATE after further investigating:
I think that URI in almost all cases is incorrect. When you go to the topics section it will be `level1/level2/level3/static/json/cards.json` so for example `Research-skills/Writing/literature-review/search-literature/static/json/cards.json`.  
I checked that it always throws 404 NOT FOUND ERROR in the console and whenever I try to change content and restart the app, nothing changes.

Could you maybe test it and say whether it is the same for you? @thierrylahaije

**Comment by thierrylahaije** [comment]
Hey @krzysztof99xd,

This 404 error you are seeing is because it is trying to load the home cards on a other page than the index page. Something seems to go wrong there that it is still trying to load the cards file on other page then the home page. I will put this into an issue.
