### ISSUE TITLE
Additional sass installation necessary when first time running the project?

### ISSUE THREAD

**Issue by krzysztof99xd** [tilburgsciencehub/website-flask#13]
I encountered an issue when first time running the app.
Part of the traceback here:
` raise FilterError( webassets.exceptions.FilterError: scss: subprocess returned a non-success result code: 1, stdout=, stderr='sass' is not recognized as an internal or external command.`

I solved by installing scss with the following command: `npm install sass`.
After that, I had an issue that there were some missing semicolons in bootstrap.scss file. I manually added them, saved and when rerun the website, everything was fine. Weird error, but important to keep track of so other people know how to possible overcome it.

**Comment by thierrylahaije** [comment]
Did you install the extended version of Hugo before? Because that might be the reason that I did not have this problem. Hugo extended installs sass already. I will make sure to add this to the readme!
