### ISSUE TITLE
Katex Formulas not displaying correctly

### ISSUE THREAD

**Issue by thierrylahaije** [tilburgsciencehub/website-flask#14]
The way people use katex is inconsistent which gives problems during rendering. Some people forget to add the $ sign in front and at the end of a variable, which was not really an issue for some reason in Hugo, but in Flask this makes applying these Katex Formulas way harder. We should fix the katex boxes in content and make sure it is used correctly applied in all content.

Steps:
1. We need to identify which pages have Katex problems and solve these problems manually in the content.
2. Fix the style guide and make sure it is clear for people how to use Katex.

Examples:
- Random Effects Model 
- The First-Difference Estimator
- Local Randomization Approach
- Sharp RD Designs

**Comment by krzysztof99xd** [comment]
I was doing some research on that. I think that none of the formulas are displayed correctly. When I run the website locally I cannot find any formula displayed nicely. I checked that most of the formulas are written the same way as it is written in the hugo page. Something is wrong here and it is not about inconsistency in using katex. The formulas seem to be not recognized at all
