### ISSUE TITLE
Think about some pre commits checks or some kind of instructions for contribuitions

### ISSUE THREAD

**Issue by krzysztof99xd** [tilburgsciencehub/website-flask#22]
So as we discussed during the meeting we should come up with some kind of pre-commit checks to standardize the commits. 
I know that on the onboarding page, there are some guidelines about code style (Coding guidelines section)  but at the moments link do not work.

If we decide on creating a manual checklist what should be included there?
 - codeblocks
 - tables
 - mathematical formula (katex)
 - each article should have at least title, description, keywords, weight, date and some content (so files are parsed correctly when inserting to the database)
  - mutiple authors should be separated by coma in the author field in the article but without space in between
  
When it comes to checks? I will look into it whether some of them could be automated or not. `lint checks`? Hannes was saying about some git actions.

**Comment by thierrylahaije** [comment]
- [ ] Check Language & Structure of codeblocks
- [ ] Enter in front of lists
- [ ] Codeblocks in lists need to be tabbed

**Comment by thierrylahaije** [comment]
For the breaks in front of lists, I started a new file called check_files.py. In there, I created a first attempt, but this still needs to be adjusted.

**Comment by thierrylahaije** [comment]
Moved this to issue #67, to make sure we update the style guide, so everyone knows how it works and we prevent errors.
