### ISSUE TITLE
Adding a new topic in the database throws an error

### ISSUE THREAD

**Issue by krzysztof99xd** [tilburgsciencehub/website-flask#24]
When I added a new article under topics section and ran content_to_db.py` script I got the following error: 

`File "_path_\website-flask\content_to_db.py", line 150, in <module>
    fill_database(topic_folder)
  File "_path_-\website-flask\content_to_db.py", line 148, in fill_database
    process_article(md_file_path, folder_id)
  File "_path_\website-flask\content_to_db.py", line 126, in process_article
    int(weight.group(1)) if weight else None, author.group(1) if author else None, file_content)
UnboundLocalError: local variable 'file_content' referenced before assignment` 

UPDATE after further research: 
So this error appeared only when the article was empty (empty md file). We need to make sure that we catch this kind of things when inserting to the database. Will write it down to the checks 
Despite having correctly formatted a new file, the file is not displayed on the website :/ . It is added to the database, I checked it.
So when deleting the database and later rerunning `content_to_db.py` file, it is displayed on the website. Nevertheless, also some articles appeared twice on the website. I will need to check why. But this is a good lead.

**Comment by thierrylahaije** [comment]
Fixed in PR #32
