### ISSUE TITLE
fix stretched layout

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website-flask#3]
I've seen that when there is no pub date available, the sharing buttons stretch tremendously.

<img width="763" alt="image" src="https://github.com/tilburgsciencehub/website-flask/assets/16557730/1878986d-2590-4e49-ba85-ad9c4a569e84">

See http://127.0.0.1:5000/building-blocks/develop-your-research-skills/learn-to-code/learn-open-interpreter.

Can you fix this?

**Comment by thierrylahaije** [comment]
@hannesdatta Issue is fixed. When given push rights I will add the updates.

**Comment by hannesdatta** [comment]
Please push. Thanks. You have the rights now. If not, send me a DM/use WhatsApp.

**Comment by krzysztof99xd** [comment]
@thierrylahaije  @hannesdatta  can we close this issue?
