### ISSUE TITLE
align layout/color scheme

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website-flask#35]
Can you please align the layout of the new flask site with what we currrently use at TSH?

What we need:
<img width="1417" alt="image" src="https://github.com/tilburgsciencehub/website-flask/assets/16557730/1dbd2114-b79a-4586-aa8d-87deb7712c49">

What it is right now:
<img width="1423" alt="image" src="https://github.com/tilburgsciencehub/website-flask/assets/16557730/8a17ace1-0a43-4a8d-b0dc-9efdcc50b395">

A few observations:
- logo isn't correct, both in colors as well as with the "supported by" slogan
- the menu isn't the same - e.g., boldifying menu items
- I may be wrong but I also sense we are not using the same fonts - across all sites
- fix text in footer
<img width="682" alt="image" src="https://github.com/tilburgsciencehub/website-flask/assets/16557730/086a2c8e-7554-413c-b25e-71f9b248b310">

- also some other minor things here and there, e.g.,
<img width="241" alt="image" src="https://github.com/tilburgsciencehub/website-flask/assets/16557730/b2a911d8-71d7-4cfa-9681-7b2e241acc46">
vs. 
<img width="409" alt="image" src="https://github.com/tilburgsciencehub/website-flask/assets/16557730/a1db8e93-f6ed-4d6a-8bf9-80b41224e2f8">
- date of posts don't need to show
<img width="918" alt="image" src="https://github.com/tilburgsciencehub/website-flask/assets/16557730/83dee1fe-18e7-4827-8a85-565505b44734">
- also, "join community" is disabled on the main tsh website - hide here as well
- click on the contribution button throws a 404
<img width="1032" alt="image" src="https://github.com/tilburgsciencehub/website-flask/assets/16557730/e7011131-f63e-4a18-9048-d9a18d14e439">

__Deliverable__

Can you please make the necessary changes to the templates, fonts, etc. so that the site looks like the current version of Tilburg Science Hub? Thanks.

**Comment by thierrylahaije** [comment]
Layout issues have been fixed in PR #42
