### ISSUE TITLE
have "related post" section

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website-flask#37]
__Background:__

The Hugo site has a related post section, which is absent in Flask.

<img width="927" alt="image" src="https://github.com/tilburgsciencehub/website-flask/assets/16557730/17b9d149-8e77-4418-a735-3ce12ba43973">

We require this section to be better able to let users 'click to the next best article'. I wouldn't want to launch without it, to be honest.

__Deliverable:__

- Build the "tech" behind being able to have such a section: add it to the html templates, have a way to fetch 'related' articles from the database
- Write a script (e.g., in Python) that determines, for every article, potentially related posts to be served in this section. This algorithm can be quite simple for now (e.g., draw randomly from any post within the category that is one level HIGHER than the current category - to nudge people to read left and right). We can refine this algorithm later on in a separate project with some of our data scientists.

**Comment by thierrylahaije** [comment]
The basic algorithm function has been made and implemented in the Flask Application.
