### ISSUE TITLE
fix docker file

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website-flask#39]
- Fix bugs: I was trying to build the container and launch it but it didn't work.
- In addition, Docker is using the Flask development server rather than NGINX.

**Comment by hannesdatta** [comment]
I have
- updated the dockerfile: now runs faster (when rebuilding)
- stopped using the Flask development server but instead enabled gunicorn, like we do at music-to-scrape.org
- wrapped the dockerfile in a docker-compose.yml so that we will be able to launch multiple services at once (e.g., one doing our web analytics in the future, another one maybe for a recommendation API etc.)
- updated the README for running instructions:
`docker compose build`
`docker compose up -d`

The site is then available at `localhost:8000`.

This PR looks mergeable. I leave it up to @thierrylahaije and @krzysztof99xd to call the shots.

**Comment by krzysztof99xd** [comment]
I have checked it! All looks fine to me!
