### ISSUE TITLE
recently published box empty

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website-flask#44]
<img width="380" alt="image" src="https://github.com/tilburgsciencehub/website-flask/assets/16557730/be99b524-4592-4773-a216-46bd6d6889ce">

Can you check why this box is empty and how to fix it?

**Comment by thierrylahaije** [comment]
Recently published has been added. The function uses date_modified if used for articles, otherwise it uses date. Users need to make sure that they add the date_modified when they modify an article to update the date.
