### ISSUE TITLE
final fixes

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website-flask#50]
fix colors:

![image](https://github.com/tilburgsciencehub/website-flask/assets/16557730/394f6c5f-b849-4f4d-a7f4-91df6f93bcc8)

icons do not render

![image](https://github.com/tilburgsciencehub/website-flask/assets/16557730/148e94d4-d1af-4d76-b848-709f89d2ac11)

site stretch

![image](https://github.com/tilburgsciencehub/website-flask/assets/16557730/4ca00b67-ad50-43a5-9eb2-4e19b4c8dd5c)

have same tsh colors in icon:

![image](https://github.com/tilburgsciencehub/website-flask/assets/16557730/eddafbad-6f22-444c-adfe-0fe8e1308dc0)

some weird breadcrumbs:

![image](https://github.com/tilburgsciencehub/website-flask/assets/16557730/63ab2bd2-f790-48a1-8796-28aea02e269c)

See whether you can fix this:

![image](https://github.com/tilburgsciencehub/website-flask/assets/16557730/1dc1bd28-747c-49d2-9412-cd132d523c21)

rendering issues on contributor page + make sure it is in sync w/ tsh's page

![image](https://github.com/tilburgsciencehub/website-flask/assets/16557730/14cc3b6a-cc50-4790-8e28-cae1725cb167)

**Comment by krzysztof99xd** [comment]
For the last point the fix is in #56

**Comment by krzysztof99xd** [comment]
Hey @hannesdatta  I was looking at the issues. I was comparing the current website and current flask version and I cannot figure it out which icons exactly do not render?

**Comment by thierrylahaije** [comment]
Issues fixed, except for breadcrumb since this issue was not visible. Created a new issue for the breadcrumbs.
