### ISSUE TITLE
prepare detailed move strategy

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website-flask#54]
how to move the project? switch repos, move issues, etc.?

prepare a strategy & timeline for our team.

**Comment by thierrylahaije** [comment]
Steps before deployment:

- [ ] Step 1: Move new content -> remember to skip the Katex parts.
- [ ] Step 2: Clean up repository. 
- [ ] Step 3: Check for vulnerabilities -> create file with all necessary variables that need to be secret
- [ ] Step 4: Connect to subdomain 
- [ ] Step 5: Check all articles for errors -> divide this among the team?
- [ ] Step 6: Process last errors 
- [ ] Step 7: Revise all articles
- [ ] Step 8: Moving to main domain -> We need to think about whether we want to:

1. Merge the flask repository in the main website repository -> in this case, we need to back up the old version, but we can keep the issues where they are.
2. Connect the new flask repository to the main domain -> in this case, the old repository can remain in private as a backup, but we need to move the open issues to the new repository. 

- [ ] Step 9: After deployment, we need to check the statistics on the search console, google analytics and the netlify/aws logs to see how everything is working.

**Comment by thierrylahaije** [comment]
@krzysztof99xd If you could do step 1 (since you know where the katex problems are), I will take care today of steps 2 and 3.

**Comment by thierrylahaije** [comment]
@hannesdatta the first steps are now done. Ready for lift off to subdomain in 3, 2, 1! [🚀](https://emojipedia.org/rocket)
