### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by thierrylahaije** [tilburgsciencehub/website-flask#61]
@hannesdatta found an error sometimes occurs with the breadcrumbs. Try to reproduce the problem and see where it comes from.

**Comment by hannesdatta** [comment]
http://localhost:8070/topics/Visualization/reporting-tables/reportingtables/pandas-latex-tables/?utm_campaign=referral-short

![image](https://github.com/tilburgsciencehub/website-flask/assets/16557730/aafeba7b-6e5e-4e4d-ad09-09c2fcff18da)

**Comment by krzysztof99xd** [comment]
We need to exclude the Urchin Tracking Module (UTM) from inserting it into breadcrumps.
