### ISSUE TITLE
fix: bullet parser off?

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website-flask#63]
![image](https://github.com/tilburgsciencehub/website-flask/assets/16557730/1ce0991b-5d05-4597-a396-70d2d6488b28)

http://localhost:8070/topics/Computer-Setup/develop-coding-skills/coding-practices/principles-good-coding/#language-specific-style-guides

**Comment by hannesdatta** [comment]
also here:

![image](https://github.com/tilburgsciencehub/website-flask/assets/16557730/fc3e8a7f-89af-4151-b3cc-87b48e1ec894)


http://localhost:8070/topics/Collect-store/data-collection/surveys/qualtrics-exporting-data/

**Comment by thierrylahaije** [comment]
Both seem correct now when I run it locally, I cannot reproduce this issue. I checked it with Google Chrome, Firefox and Safari. 

<img width="841" alt="image" src="https://github.com/tilburgsciencehub/website-flask/assets/65568251/4b54a6b6-4053-4c68-b524-a5a28dc89673">

<img width="841" alt="image" src="https://github.com/tilburgsciencehub/website-flask/assets/65568251/947763a9-ec66-4d62-81c4-b25bfc1f7e1c">
