### ISSUE TITLE
Adjust style-guide

### ISSUE THREAD

**Issue by thierrylahaije** [tilburgsciencehub/website-flask#67]
Clarify listing space not allowed in first level of listing:
<img width="669" alt="image" src="https://github.com/tilburgsciencehub/website-flask/assets/65568251/7e1991cd-371d-437f-85fd-b54d6c035104">

**Comment by thierrylahaije** [comment]
- [ ] language & structure of codeblocks
- [ ] no space in front of first-level listing
- [ ] break in front of lists
- [ ] codeblocks in lists need to be tabbed
- [ ] tables
- [ ] mathematical formula (katex)
- [ ] each article should have at least title, description, keywords, weight, date and some content (so files are parsed correctly when inserting to the database)
- [ ] multiple authors should be separated by coma in the author field in the article but without space in between

**Comment by thierrylahaije** [comment]
@krzysztof99xd done!

**Comment by krzysztof99xd** [comment]
Thank you!
